const PRICES = {
	"Absolut Vodka": 6,
	"Absolut Citron": 6,
	"Absolut Kurant": 6,
	Advocaat: 5,
	Applejack: 7,
	"Apple brandy": 6,
	Absinthe: 4,
	Amaretto: 5,
	"Angostura Bitters": 1,
	"Añejo rum": 5,
	"Apricot brandy": 4,
	"Baileys irish cream": 5,
	"Bacardi Limon": 4,
	Beer: 2,
	Brandy: 6,
	Bitters: 2,
	"Black Sambuca": 6,
	"Blended whiskey": 5,
	"Blended Scotch": 5,
	"Blue Curacao": 3,
	"Banana liqueur": 6,
	"Blackberry brandy": 4,
	"Blackcurrant cordial": 3,
	Bourbon: 4,
	Campari: 3,
	"Carbonated water": 1,
	Cinnamon: 2,
	"Coca-Cola": 2,
	Cointreau: 3,
	Cachaca: 1,
	Cherry: 1,
	"Cherry brandy": 3,
	"Cherry Heering": 3,
	"Champagne Flute": 2,
	Champagne: 5,
	Coffee: 2,
	"Coffee liqueur": 4,
	"Coffee brandy": 5,
	Cognac: 7,
	Corona: 3,
	"Cranberry juice": 1,
	"Cranberry vodka": 1,
	Cream: 2,
	"Creme de Banane": 2,
	"Creme de Cassis": 2,
	"Creme de Mure": 2,
	"Club soda": 1,
	"Creme de Cacao": 3,
	"Cherry Juice": 1,
    "Chocolate liqueur": 6,
    "Chambord raspberry liqueur":5,
	Cider: 4,
	"Coconut Liqueur": 5,
	"Crown Royal": 6,
	"Dark rum": 4,
	"Dark Rum": 4,
	"demerara Sugar": 1,
	"Dry Vermouth": 5,
	"Dubonnet Rouge": 6,
	"Elderflower cordial": 4,
	"Egg White": 2,
	"Egg yolk": 2,
	Everclear: 4,
	Espresso: 2,
	Fanta: 2,
	Frangelico: 4,
	Falernum: 3,
	"Fruit punch": 3,
	Firewater: 2,
	Galliano: 6,
	Gin: 3,
	"Green Creme de Menthe": 4,
	gin: 3,
	"Ginger ale": 3,
	"Ginger Beer": 2,
	Goldschlager: 6,
	"Grand Marnier": 5,
	"Grapefruit juice": 1,
	"Grain alcohol": 4,
	"Grape Soda": 2,
	Grenadine: 5,
	"Green Chartreuse": 4,
	"Godiva liqueur": 6,
	"Heavy cream": 5,
	"Hot Chocolate": 2,
	"Hot Damn": 3,
	"Irish cream": 5,
	"Irish whiskey": 6,
	"Irish Whiskey": 6,
	Jägermeister: 6,
	"Jack Daniels": 7,
	"Jim Beam": 6,
	Ice: 0,
	Kahlua: 5,
	"Kiwi liqueur": 4,
	Kiwi: 1,
	"Kool-Aid": 6,
	Lager: 7,
	"Lemon Juice": 1,
	"lemon juice": 1,
	"Lemon juice": 1,
	"Lemon peel": 2,
	Lemonade: 2,
	"Lillet Blanc": 4,
	"Light cream": 2,
	"Light rum": 4,
	"Lime juice": 1,
	Lime: 1,
	Milk: 2,
	"Malibu rum": 6,
	"Maraschino cherry": 5,
	"Maraschino Cherry": 5,
	Mezcal: 4,
	Mint: 2,
	"maraschino liqueur": 5,
	"Midori melon liqueur": 6,
	"Mountain Dew": 2,
	Nutmeg: 2,
	"Orange juice": 1,
	"Orange bitters": 1,
	"Orange Bitters": 1,
	"Peppermint extract": 2,
	Port: 6,
	"Peach nectar": 2,
	"Peach schnapps": 3,
	"Peach Vodka": 6,
	"Peachtree schnapps": 4,
	"Pisang Ambon": 5,
	"Pineapple juice": 1,
	Pisco: 2,
	"Passion fruit juice": 1,
	"Powdered sugar": 0,
	Prosecco: 4,
	"Rye Whiskey": 5,
	Ricard: 5,
	Rum: 5,
	Rose: 4,
	"Rye whiskey": 6,
	"Soda water": 1,
	"Red wine": 5,
	"Raspberry vodka": 5,
	Sambuca: 5,
	Sherry: 2,
	"Spiced rum": 6,
	"Strawberry schnapps": 4,
	Sugar: 1,
	"Sugar syrup": 1,
	Scotch: 5,
	"Sloe gin": 4,
	"Southern Comfort": 4,
	Sprite: 2,
	Surge: 2,
	"Sweet Vermouth": 6,
	"Triple sec": 7,
	"Tomato juice": 1,
	Tequila: 5,
    Vodka: 5,
    "Vanilla vodka":5,
	Vermouth: 6,
	Water: 1,
	Wormwood: 1,
	"Worcestershire sauce": 6,
	"Wild Turkey": 4,
	"151 proof rum": 5,
	Wine: 6,
	Whiskey: 6,
	Whisky: 6,
	"White Rum": 5,
    "Yukon Jack": 7,
    Zima:7,
};

export default PRICES;